# Workshop Python

# **Descrição:**
Este módulo destina-se à introdução de algumas bibliotecas importantes, como *Numpy*, assim como à manipulação de vetores e construção de funções e classes. Como projeto final, pretende-se que o utilizador crie programa que calcule o conjunto de coordenadas de um plano cartesiano que tenha a menor distância euclidiana em relação à origem. 

# Numpy - Operações de Base

O conjunto de exercícios em baixo pretendem apresentar as vantagens da utilização do pacote Numpy para ciração de arrays e vetores multidimensionais.


1 - Crie um vetor com dois elementos int (à escolha do utilizador)

In [1]:
import numpy as np

vetor = np.array([1, 2])

print(vetor)

[1 2]


2 - Escreva um programa para testar se algum dos elementos de um determinado vetor é diferente de zero.

In [2]:
print(np.any(vetor))
vetor_nulo = np.array([0,0])
print(np.any(vetor_nulo))

True
False


3-Escreva programa para criar uma comparação baseada em elementos (maior, maior_equal, menor e menor_equal) de dois vetores.

In [3]:
vetor1 = np.array([3, 5])
vetor2 = np.array([2, 5])


print(np.greater(vetor1, vetor2))

print(np.greater_equal(vetor1, vetor2))

print(np.less(vetor1, vetor2))

print(np.less_equal(vetor1, vetor2))

[ True False]
[ True  True]
[False False]
[False  True]


4 - Escreva um programa NumPy para criar um vetor com valores de 0 a 20 e alterar o sinal dos números no intervalo de 9 a 15.

In [4]:
vetor3 = np.arange(20)
print(vetor3)
vetor3[(vetor3 >= 9) & (vetor3 <= 15)] *= -1
print(vetor3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19]


5 - Crie um vetor com 10 elementos que estejam contidos no intervalo 0-10

In [7]:
vetor4 = np.random.randint(100, size=10)
print(vetor4)

[ 3 33 68 86 66 21 94 38 92 42]


# Matrizes 2D e 3D

Neste módulo apresentam-se alguns exemplo de matipulação de matrizes 2D e 3D.

1 - Escreva um programa NumPy para criar uma matriz 3x3 com valores que variam de 2 a 10.

In [8]:
matriz =  np.arange(2, 11).reshape(3,3)
print(matriz)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


 2 - Escreva um programa  para criar uma matriz 8x8 e preenchê-lo com um padrão xadrez.

In [9]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


3 - Escreva um programa para extrair todos os elementos da primeira e da quarta colunas de uma determinada matriz (4x4).

In [10]:
matriz1 = np.arange(0,16).reshape((4, 4))
print(matriz1)
print(matriz1[:, [0,3]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  3]
 [ 4  7]
 [ 8 11]
 [12 15]]


# Operações no Plano Cartesiano


1 - Crie um vetor com todas as combinações possíveis de pontos no plano 2D até ao número 10

In [12]:
coordinates = []

for x in range(11):
    for y in range(11):
        coordinates.append((x, y))
print(coordinates)

[(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (0, 8), (0, 9), (0, 10), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (1, 9), (1, 10), (2, 0), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (2, 8), (2, 9), (2, 10), (3, 0), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (3, 8), (3, 9), (3, 10), (4, 0), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7), (4, 8), (4, 9), (4, 10), (5, 0), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 7), (5, 8), (5, 9), (5, 10), (6, 0), (6, 1), (6, 2), (6, 3), (6, 4), (6, 5), (6, 6), (6, 7), (6, 8), (6, 9), (6, 10), (7, 0), (7, 1), (7, 2), (7, 3), (7, 4), (7, 5), (7, 6), (7, 7), (7, 8), (7, 9), (7, 10), (8, 0), (8, 1), (8, 2), (8, 3), (8, 4), (8, 5), (8, 6), (8, 7), (8, 8), (8, 9), (8, 10), (9, 0), (9, 1), (9, 2), (9, 3), (9, 4), (9, 5), (9, 6), (9, 7), (9, 8), (9, 9), (9, 10), (10, 0), (10, 1), (10, 2), (10, 3), (10, 4), (10, 5), (10, 6), (10, 7), (10, 8), (10, 9), (10, 10)]


# Projeto

Um aeroporto fornece um conjunto de coordenadas (X,Y) tirados em vários instantes (ficheiros t1.txt, t2.txt, t3.txt), com a localização de 3 drones que estão ao serviço nesse dia e partem, ambos, do mesmo ponto. Um deles encontra-se danificado ( que apresentará, à partida, a menor distância euclideana média ao local de origem). Faça um programa que identifique o drone danificado. Poderá apresentar o resultado como int 